# Generated by Django 3.1.7 on 2021-03-08 04:43

from django.db import migrations, models
import edc_base.model_validators.date
import edc_base.utils
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('potlako_follow', '0003_call_log_logentry'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='logentry',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='call_reason',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='survival_status',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='time_of_day',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='time_of_week',
        ),
        migrations.AddField(
            model_name='logentry',
            name='alt_cell_contact_fail',
            field=models.CharField(choices=[('no_response', 'Phone rang, no response but voicemail left'), ('no_response_vm_not_left', 'Phone rang no response and no option to leave voicemail'), ('disconnected', 'Phone did not ring/number disconnected'), ('number_changed', 'No longer the phone number of BHP participant'), ('N/A', 'Not Applicable')], default='N/A', max_length=100, verbose_name='Why was the contact to [ ] unsuccessful?'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='alt_tel_contact_fail',
            field=models.CharField(choices=[('no_response', 'Phone rang, no response but voicemail left'), ('no_response_vm_not_left', 'Phone rang no response and no option to leave voicemail'), ('disconnected', 'Phone did not ring/number disconnected'), ('number_changed', 'No longer the phone number of BHP participant'), ('N/A', 'Not Applicable')], default='N/A', max_length=100, verbose_name='Why was the contact to [ ] unsuccessful?'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='cell_alt_contact_fail',
            field=models.CharField(choices=[('no_response', 'Phone rang, no response but voicemail left'), ('no_response_vm_not_left', 'Phone rang no response and no option to leave voicemail'), ('disconnected', 'Phone did not ring/number disconnected'), ('number_changed', 'No longer the phone number of BHP participant'), ('N/A', 'Not Applicable')], default='N/A', max_length=100, verbose_name='Why was the contact to [ ] unsuccessful?'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='cell_contact_fail',
            field=models.CharField(choices=[('no_response', 'Phone rang, no response but voicemail left'), ('no_response_vm_not_left', 'Phone rang no response and no option to leave voicemail'), ('disconnected', 'Phone did not ring/number disconnected'), ('number_changed', 'No longer the phone number of BHP participant'), ('N/A', 'Not Applicable')], default='N/A', max_length=100, verbose_name='Why was the contact to [ ] unsuccessful?'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='cell_resp_person_fail',
            field=models.CharField(choices=[('no_response', 'Phone rang, no response but voicemail left'), ('no_response_vm_not_left', 'Phone rang no response and no option to leave voicemail'), ('disconnected', 'Phone did not ring/number disconnected'), ('number_changed', 'No longer the phone number of BHP participant'), ('N/A', 'Not Applicable')], default='N/A', max_length=100, verbose_name='Why was the contact to [ ] unsuccessful?'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='home_visit',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('never_answer', 'Decide to do home visit because the phone is never answered'), ('requested_home_visit', 'Participants prefers/requested a home visit'), ('OTHER', 'Other reason ...')], default='N/A', max_length=50, verbose_name='Perform home visit.'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='home_visit_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Other reason, please specify ...'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='phone_num_success',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('subject_cell', 'subject_cell'), ('subject_cell_alt', 'subject_cell_alt'), ('subject_phone', 'subject_phone'), ('subject_phone_alt', 'subject_phone_alt'), ('subject_work_phone', 'subject_work_phone'), ('indirect_contact_cell', 'indirect_contact_cell'), ('indirect_contact_phone', 'indirect_contact_phone'), ('caretaker_cell', 'caretaker_cell'), ('caretaker_tel', 'caretaker_tel'), ('none_of_the_above', 'None of the above')], default=None, max_length=172, verbose_name='Which number(s) were you successful in reaching?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='phone_num_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('subject_cell', 'subject_cell'), ('subject_cell_alt', 'subject_cell_alt'), ('subject_phone', 'subject_phone'), ('subject_phone_alt', 'subject_phone_alt'), ('subject_work_phone', 'subject_work_phone'), ('indirect_contact_cell', 'indirect_contact_cell'), ('indirect_contact_phone', 'indirect_contact_phone'), ('caretaker_cell', 'caretaker_cell'), ('caretaker_tel', 'caretaker_tel')], default=None, max_length=154, verbose_name='Which phone number(s) was used for contact?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='prev_study',
            field=models.CharField(default=None, max_length=100, verbose_name='Previous Study Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='study_maternal_identifier',
            field=models.CharField(default=None, max_length=50, verbose_name='Study maternal Subject Identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='subject_identifier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='logentry',
            name='tel_alt_contact_fail',
            field=models.CharField(choices=[('no_response', 'Phone rang, no response but voicemail left'), ('no_response_vm_not_left', 'Phone rang no response and no option to leave voicemail'), ('disconnected', 'Phone did not ring/number disconnected'), ('number_changed', 'No longer the phone number of BHP participant'), ('N/A', 'Not Applicable')], default='N/A', max_length=100, verbose_name='Why was the contact to [ ] unsuccessful?'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='tel_contact_fail',
            field=models.CharField(choices=[('no_response', 'Phone rang, no response but voicemail left'), ('no_response_vm_not_left', 'Phone rang no response and no option to leave voicemail'), ('disconnected', 'Phone did not ring/number disconnected'), ('number_changed', 'No longer the phone number of BHP participant'), ('N/A', 'Not Applicable')], default='N/A', max_length=100, verbose_name='Why was the contact to [ ] unsuccessful?'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='tel_resp_person_fail',
            field=models.CharField(choices=[('no_response', 'Phone rang, no response but voicemail left'), ('no_response_vm_not_left', 'Phone rang no response and no option to leave voicemail'), ('disconnected', 'Phone did not ring/number disconnected'), ('number_changed', 'No longer the phone number of BHP participant'), ('N/A', 'Not Applicable')], default='N/A', max_length=100, verbose_name='Why was the contact to [ ] unsuccessful?'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='work_contact_fail',
            field=models.CharField(choices=[('no_response', 'Phone rang, no response but voicemail left'), ('no_response_vm_not_left', 'Phone rang no response and no option to leave voicemail'), ('disconnected', 'Phone did not ring/number disconnected'), ('number_changed', 'No longer the phone number of BHP participant'), ('N/A', 'Not Applicable')], default='N/A', max_length=100, verbose_name='Why was the contact to [ ] unsuccessful?'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='appt',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default=None, max_length=7, verbose_name='Is the participant willing to schedule an appointment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logentry',
            name='call_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date of contact attempt'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='may_call',
            field=models.CharField(choices=[('Yes', 'Yes, we may continue to contact the participant.'), ('No', 'No, participant has asked NOT to be contacted again.'), ('N/A', 'Not Applicable')], default='Yes', max_length=10, verbose_name='May we continue to contact the participant?'),
        ),
    ]
