# Generated by Django 3.1.7 on 2021-03-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potlako_follow', '0004_auto_20210308_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='prev_study',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='study_maternal_identifier',
        ),
    ]
